---
- hosts: master
  gather_facts: no
  tasks:
    - name: Print some debug information 
      vars: 
        msg: |
            HOST Variables ("hostvars"):
            --------------------------------
            {{ hostvars | to_nice_json }} 

      debug: 
        msg: "{{ msg.split('\n') }}"       
      tags: debug_info          
    # login to the cluster rhsso and get a token  
    # - name: Generate RH-SSO auth token for admin user
    #   uri:
    #     url: "https://{{ rhsso_route }}/auth/realms/{{ rhsso_admin_realm }}/protocol/openid-connect/token"
    #     method: POST
    #     body: "client_id=admin-cli&username={{ rhsso_admin_username }}&password={{ rhsso_admin_password_cmd.stdout }}&grant_type=password"
    #     validate_certs: "{{ rhsso_validate_certs }}"
    #   register: rhsso_auth_response
    #   retries: 20
    #   delay: 2
    #   until: rhsso_auth_response.status == 200


# do something with the 3scale API  